---

- block:
  - name: Check if cloud config exists
    stat:
      path: /etc/cloud/templates/hosts.debian.tmpl
    register: cloud_hosts_template

  - name: Set hostname
    hostname:
      name: "{{ hostname }}"
    register: hostname_set

  - name: Set /etc/hostname
    copy:
      content: "{{ hostname }}"
      dest: /etc/hostname
      mode: 0644
      owner: root
      group: root
    register: hostname_file

  - name: Set /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      mode: 0644
      owner: root
      group: root
    register: hosts_file

  - name: Replace cloud hostname file if exists
    template:
      src: hosts.j2
      dest: /etc/cloud/templates/hosts.debian.tmpl
      mode: 0644
      owner: root
      group: root
    register: cloud_hosts_file_replace
    when: cloud_hosts_template.stat.exists

  - name: Reboot if hosts or hostname has changed
    reboot:
    when: >
      - (hostname_set is changed) or
      - (hosts_file is changed) or
      - (hostname_file is changed) or
      - (cloud_hosts_file_replace is changed)
  become: true
