---

- name: Deploy main landing page file
  template:
    src: main.j2
    dest: "{{ webroot }}/main.html"
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: main

- name: Deploy css style sheet
  copy:
    src: styleSheet.css
    dest: "{{ webroot }}/styles/styleSheet.css"
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: css

- name: Find main page static files
  command: "ls {{ playbook_dir }}/roles/main_page/files/"
  register: main_page_static_files
  delegate_to: localhost

- name: Deploy main page static files
  copy:
    src: "{{ main_files }}"
    dest: "{{ webroot }}/static/main/"
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ main_page_static_files.stdout_lines }}"
  loop_control:
    loop_var: main_files
